export const APPROVED_PROTAGONIST_FRAME_WIDTH = 64;
export const APPROVED_PROTAGONIST_FRAME_HEIGHT = 96;
export const APPROVED_PROTAGONIST_REVIEW_SCALE = 2;
export const APPROVED_PROTAGONIST_GAME_SCALE = 1;
